In [1]:
#class imbalance >> when one class has higher percentage
#handle class imbalance problem.
'''to handle this we have 3 types
1.upsamping/oversampling
2.downsampling/undersampling
3.SMOTE (synthetic minority oversampling technique)'''

'to handle this we have 3 types\n1.upsamping/oversampling\n2.downsampling/undersampling\n3.SMOTE (synthetic minority oversampling technique)'

In [3]:
import numpy as np
import pandas as pd
import seaborn as sns

np.random.seed(1) #it will regenerate the same data point again (seed will not generate random number it only generate once)

no_sample = 1000
class_0_ratio = 0.9
class_1_ratio = 0.1
no_class_0= int(no_sample* class_0_ratio)
no_class_1 = int(no_sample * class_1_ratio)

In [4]:
no_class_0, no_class_1

(900, 100)

In [8]:
class_0 = {'Feature1':np.random.normal(0,1,no_class_0),
           'Feature2':np.random.normal(0,1,no_class_0),
           'Target':[0]*no_class_0}#here we get mean of dataset 0, std=1 and 900data points
#np.random.normal(mean,std,number_of_points)
class_0_df = pd.DataFrame(class_0)
class_0_df

     Feature1  Feature2  Target
0   -0.098819 -0.551358       0
1   -0.270149 -0.604188       0
2    1.745068  1.234969       0
3   -0.180558 -0.103111       0
4   -0.202378 -0.368854       0
..        ...       ...     ...
895  0.747622 -2.094381       0
896  0.943634 -0.385521       0
897 -0.425562 -1.408973       0
898  0.805778  0.076441       0
899  0.056853 -0.412497       0

[900 rows x 3 columns]

In [9]:
class_1 = {'Feature1':np.random.normal(0,1,no_class_1),
           'Feature2':np.random.normal(0,1,no_class_1),
           'Target':[1]*no_class_1}
class_1_df = pd.DataFrame(class_1)
class_1_df

    Feature1  Feature2  Target
0   0.482790  0.884323       1
1   0.666030  0.491177       1
2   0.104910 -1.017899       1
3  -1.563505 -1.352402       1
4   0.958643  0.877928       1
..       ...       ...     ...
95 -0.407013 -0.651176       1
96 -0.333856 -0.140700       1
97 -0.930115 -0.933276       1
98 -0.485400 -0.823021       1
99 -0.860615  0.428550       1

[100 rows x 3 columns]

In [10]:
df = pd.concat([class_0_df,class_1_df]).reset_index(drop=True)
df

     Feature1  Feature2  Target
0   -0.098819 -0.551358       0
1   -0.270149 -0.604188       0
2    1.745068  1.234969       0
3   -0.180558 -0.103111       0
4   -0.202378 -0.368854       0
..        ...       ...     ...
995 -0.407013 -0.651176       1
996 -0.333856 -0.140700       1
997 -0.930115 -0.933276       1
998 -0.485400 -0.823021       1
999 -0.860615  0.428550       1

[1000 rows x 3 columns]

In [14]:
df.Target.value_counts()

Target
0    900
1    100
Name: count, dtype: int64

In [17]:
#upsampling (making minority class to similar as majority)
df_minority = df[df['Target']==1]
df_majority = df[df['Target']==0]

In [16]:
#to making or apply sampling technique we have a library called scikit learn
from sklearn.utils import resample

In [19]:
#replace= true (With replacement) (means once a picked sample may repeatedly pick)
df_minority_upsample = resample(df_minority,replace=True, n_samples=len(df_majority),random_state=1) 
#replace = true (means with replacement (allowed to pic again the same)) (flase means not allowed)
#n_samples tells how many datapoints we need for upsampling, random_sate = we can give any number which makes to reproduce same things again and again.
df_minority_upsample

     Feature1  Feature2  Target
937  0.111296  0.368898       1
912 -0.315171  0.644545       1
972  2.095925 -1.143294       1
909  1.461578 -0.689746       1
975 -0.588576 -1.761824       1
..        ...       ...     ...
936 -0.794381 -0.258174       1
998 -0.485400 -0.823021       1
901  0.666030  0.491177       1
932  0.888369  0.362888       1
930  0.040778 -1.154675       1

[900 rows x 3 columns]

In [20]:
df_minority_upsample.head()

     Feature1  Feature2  Target
937  0.111296  0.368898       1
912 -0.315171  0.644545       1
972  2.095925 -1.143294       1
909  1.461578 -0.689746       1
975 -0.588576 -1.761824       1

In [24]:
df_upsampled = pd.concat([df_minority_upsample,df_majority]).reset_index(drop=True)
df_upsampled

      Feature1  Feature2  Target
0     0.111296  0.368898       1
1    -0.315171  0.644545       1
2     2.095925 -1.143294       1
3     1.461578 -0.689746       1
4    -0.588576 -1.761824       1
...        ...       ...     ...
1795  0.747622 -2.094381       0
1796  0.943634 -0.385521       0
1797 -0.425562 -1.408973       0
1798  0.805778  0.076441       0
1799  0.056853 -0.412497       0

[1800 rows x 3 columns]

In [25]:
df_upsampled['Target'].value_counts()

Target
1    900
0    900
Name: count, dtype: int64

In [27]:
#downsampling
df_majority_downsample =resample(df_majority,replace=False,n_samples=len(df_minority),random_state=1)
df_majority_downsample

     Feature1  Feature2  Target
860  0.780678  0.648790       0
880  0.215341  1.161142       0
874 -0.603646 -0.374507       0
780  0.363966 -1.178784       0
525  0.992134  0.629625       0
..        ...       ...     ...
494 -0.492905  0.584679       0
255 -0.696128  0.629411       0
672 -1.198305 -1.604342       0
481 -0.102980  0.715686       0
838  0.300088 -0.072041       0

[100 rows x 3 columns]

In [28]:
df_downsample = pd.concat([df_majority_downsample,df_minority]).reset_index(drop=True)
df_downsample

     Feature1  Feature2  Target
0    0.780678  0.648790       0
1    0.215341  1.161142       0
2   -0.603646 -0.374507       0
3    0.363966 -1.178784       0
4    0.992134  0.629625       0
..        ...       ...     ...
195 -0.407013 -0.651176       1
196 -0.333856 -0.140700       1
197 -0.930115 -0.933276       1
198 -0.485400 -0.823021       1
199 -0.860615  0.428550       1

[200 rows x 3 columns]