In [3]:
import pandas as pd
import numpy as np
data = {
    'name':['alice','bob','charlie','David','Emma'],
    'math': [88,75,92,60,85],
    'science':[90,80,78,70,95]
}
df = pd.DataFrame(data)
df

      name  math  science
0    alice    88       90
1      bob    75       80
2  charlie    92       78
3    David    60       70
4     Emma    85       95

In [5]:
#apply() function, we can you function for all data using apply
df['total marks'] = df[['math','science']].apply(lambda row: row.sum(), axis=1)
df

      name  math  science  total marks
0    alice    88       90          178
1      bob    75       80          155
2  charlie    92       78          170
3    David    60       70          130
4     Emma    85       95          180

In [7]:
col_mean = df[['math','science']].apply(lambda col : col.mean())
col_mean

math       80.0
science    82.6
dtype: float64

In [8]:
def to_grade(score):
    if score>=90:
        return 'grade A'
    elif score >=80:
        return 'grade B'
    elif score >=35:
        return 'grade C'
    else :
        return 'fail'
    
df['maths grade'] = df['math'].apply(to_grade)
df

      name  math  science  total marks maths grade
0    alice    88       90          178     grade B
1      bob    75       80          155     grade C
2  charlie    92       78          170     grade A
3    David    60       70          130     grade C
4     Emma    85       95          180     grade B

In [9]:
df['science grade'] = df['science'].apply(to_grade)

In [10]:
df

      name  math  science  total marks maths grade science grade
0    alice    88       90          178     grade B       grade A
1      bob    75       80          155     grade C       grade B
2  charlie    92       78          170     grade A       grade C
3    David    60       70          130     grade C       grade C
4     Emma    85       95          180     grade B       grade A

In [11]:
df['name'] = df['name'].map(str.capitalize)
df

      name  math  science  total marks maths grade science grade
0    Alice    88       90          178     grade B       grade A
1      Bob    75       80          155     grade C       grade B
2  Charlie    92       78          170     grade A       grade C
3    David    60       70          130     grade C       grade C
4     Emma    85       95          180     grade B       grade A

In [12]:
df['bonous math'] = df['math'].map(lambda x: x+5)
df

      name  math  science  total marks maths grade science grade  bonous math
0    Alice    88       90          178     grade B       grade A           93
1      Bob    75       80          155     grade C       grade B           80
2  Charlie    92       78          170     grade A       grade C           97
3    David    60       70          130     grade C       grade C           65
4     Emma    85       95          180     grade B       grade A           90