In [1]:
import pandas as pd
import numpy as np

In [38]:
df = pd.read_csv('hotel_bookings.csv')
df

,hotel,is_canceled,lead_time,arrival_date_year,arrival_date_month,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,...,deposit_type,agent,company,days_in_waiting_list,customer_type,adr,required_car_parking_spaces,total_of_special_requests,reservation_status,reservation_status_date
0,Resort Hotel,0,342,2015,July,27,1,0,0,2,...,No Deposit,NaN,NaN,0,Transient,0.00,0,0,Check-Out,2015-07-01
1,Resort Hotel,0,737,2015,July,27,1,0,0,2,...,No Deposit,NaN,NaN,0,Transient,0.00,0,0,Check-Out,2015-07-01
2,Resort Hotel,0,7,2015,July,27,1,0,1,1,...,No Deposit,NaN,NaN,0,Transient,75.00,0,0,Check-Out,2015-07-02
3,Resort Hotel,0,13,2015,July,27,1,0,1,1,...,No Deposit,304.0,NaN,0,Transient,75.00,0,0,Check-Out,2015-07-02
4,Resort Hotel,0,14,2015,July,27,1,0,2,2,...,No Deposit,240.0,NaN,0,Transient,98.00,0,1,Check-Out,2015-07-03
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
119385,City Hotel,0,23,2017,August,35,30,2,5,2,...,No Deposit,394.0,NaN,0,Transient,96.14,0,0,Check-Out,2017-09-06
119386,City Hotel,0,102,2017,August,35,31,2,5,3,...,No Deposit,9.0,NaN,0,Transient,225.43,0,2,Check-Out,2017-09-07
119387,City Hotel,0,34,2017,August,35,31,2,5,2,...,No Deposit,9.0,NaN,0,Transient,157.71,0,4,Check-Out,2017-09-07
119388,City Hotel,0,109,2017,August,35,31,2,5,2,...,No Deposit,89.0,NaN,0,Transient,104.40,0,0,Check-Out,2017-09-07
119389,City Hotel,0,205,2017,August,35,29,2,7,2,...,No Deposit,9.0,NaN,0,Transient,151.20,0,2,Check-Out,2017-09-07

In [39]:
print(df.isna())
#true means missing value present false me no missing values we can also use 
print(df.isnull())

        hotel  is_canceled  lead_time  arrival_date_year  arrival_date_month  \
0       False        False      False              False               False
1       False        False      False              False               False
2       False        False      False              False               False
3       False        False      False              False               False
4       False        False      False              False               False
...       ...          ...        ...                ...                 ...
119385  False        False      False              False               False
119386  False        False      False              False               False
119387  False        False      False              False               False
119388  False        False      False              False               False
119389  False        False      False              False               False

        arrival_date_week_number  arrival_date_day_of_month  \
0                          False                      False
1                          False                      False
2                          False                      False
3                          False                      False
4                          False                      False
...                          ...                        ...
119385                     False                      False
119386                     False                      False
119387                     False                      False
119388                     False                      False
119389                     False                      False

        stays_in_weekend_nights  stays_in_week_nights  adults  ...  \
0                         False                 False   False  ...
1                         False                 False   False  ...
2                         False                 False   False  ...
3                         False                 False   False  ...
4                         False                 False   False  ...
...                         ...                   ...     ...  ...
119385                    False                 False   False  ...
119386                    False                 False   False  ...
119387                    False                 False   False  ...
119388                    False                 False   False  ...
119389                    False                 False   False  ...

        deposit_type  agent  company  days_in_waiting_list  customer_type  \
0              False   True     True                 False          False
1              False   True     True                 False          False
2              False   True     True                 False          False
3              False  False     True                 False          False
4              False  False     True                 False          False
...              ...    ...      ...                   ...            ...
119385         False  False     True                 False          False
119386         False  False     True                 False          False
119387         False  False     True                 False          False
119388         False  False     True                 False          False
119389         False  False     True                 False          False

          adr  required_car_parking_spaces  total_of_special_requests  \
0       False                        False                      False
1       False                        False                      False
2       False                        False                      False
3       False                        False                      False
4       False                        False                      False
...       ...                          ...                        ...
119385  False                        False                      False
119386  False                        False                      False
119387  False                        False                      False
119388  False                        False                      False
119389  False                        False                      False

        reservation_status  reservation_status_date
0                    False                    False
1                    False                    False
2                    False                    False
3                    False                    False
4                    False                    False
...                    ...                      ...
119385               False                    False
119386               False                    False
119387               False                    False
119388               False                    False
119389               False                    False

[119390 rows x 32 columns]
        hotel  is_canceled  lead_time  arrival_date_year  arrival_date_month  \
0       False        False      False              False               False
1       False        False      False              False               False
2       False        False      False              False               False
3       False        False      False              False               False
4       False        False      False              False               False
...       ...          ...        ...                ...                 ...
119385  False        False      False              False               False
119386  False        False      False              False               False
119387  False        False      False              False               False
119388  False        False      False              False               False
119389  False        False      False              False               False

        arrival_date_week_number  arrival_date_day_of_month  \
0                          False                      False
1                          False                      False
2                          False                      False
3                          False                      False
4                          False                      False
...                          ...                        ...
119385                     False                      False
119386                     False                      False
119387                     False                      False
119388                     False                      False
119389                     False                      False

        stays_in_weekend_nights  stays_in_week_nights  adults  ...  \
0                         False                 False   False  ...
1                         False                 False   False  ...
2                         False                 False   False  ...
3                         False                 False   False  ...
4                         False                 False   False  ...
...                         ...                   ...     ...  ...
119385                    False                 False   False  ...
119386                    False                 False   False  ...
119387                    False                 False   False  ...
119388                    False                 False   False  ...
119389                    False                 False   False  ...

        deposit_type  agent  company  days_in_waiting_list  customer_type  \
0              False   True     True                 False          False
1              False   True     True                 False          False
2              False   True     True                 False          False
3              False  False     True                 False          False
4              False  False     True                 False          False
...              ...    ...      ...                   ...            ...
119385         False  False     True                 False          False
119386         False  False     True                 False          False
119387         False  False     True                 False          False
119388         False  False     True                 False          False
119389         False  False     True                 False          False

          adr  required_car_parking_spaces  total_of_special_requests  \
0       False                        False                      False
1       False                        False                      False
2       False                        False                      False
3       False                        False                      False
4       False                        False                      False
...       ...                          ...                        ...
119385  False                        False                      False
119386  False                        False                      False
119387  False                        False                      False
119388  False                        False                      False
119389  False                        False                      False

        reservation_status  reservation_status_date
0                    False                    False
1                    False                    False
2                    False                    False
3                    False                    False
4                    False                    False
...                    ...                      ...
119385               False                    False
119386               False                    False
119387               False                    False
119388               False                    False
119389               False                    False

[119390 rows x 32 columns]

In [40]:
#to get the sum we add sum function 
df.isnull().sum()

hotel                                  0
is_canceled                            0
lead_time                              0
arrival_date_year                      0
arrival_date_month                     0
arrival_date_week_number               0
arrival_date_day_of_month              0
stays_in_weekend_nights                0
stays_in_week_nights                   0
adults                                 0
children                               4
babies                                 0
meal                                   0
country                              488
market_segment                         0
distribution_channel                   0
is_repeated_guest                      0
previous_cancellations                 0
previous_bookings_not_canceled         0
reserved_room_type                     0
assigned_room_type                     0
booking_changes                        0
deposit_type                           0
agent                              16340
company                           112593
days_in_waiting_list                   0
customer_type                          0
adr                                    0
required_car_parking_spaces            0
total_of_special_requests              0
reservation_status                     0
reservation_status_date                0
dtype: int64

In [41]:
df.isna().sum()

hotel                                  0
is_canceled                            0
lead_time                              0
arrival_date_year                      0
arrival_date_month                     0
arrival_date_week_number               0
arrival_date_day_of_month              0
stays_in_weekend_nights                0
stays_in_week_nights                   0
adults                                 0
children                               4
babies                                 0
meal                                   0
country                              488
market_segment                         0
distribution_channel                   0
is_repeated_guest                      0
previous_cancellations                 0
previous_bookings_not_canceled         0
reserved_room_type                     0
assigned_room_type                     0
booking_changes                        0
deposit_type                           0
agent                              16340
company                           112593
days_in_waiting_list                   0
customer_type                          0
adr                                    0
required_car_parking_spaces            0
total_of_special_requests              0
reservation_status                     0
reservation_status_date                0
dtype: int64

In [42]:
#to drop a missing values
#before drop we will copy the actual file and edit the copied files 
df_copy = df
df_copy

,hotel,is_canceled,lead_time,arrival_date_year,arrival_date_month,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,...,deposit_type,agent,company,days_in_waiting_list,customer_type,adr,required_car_parking_spaces,total_of_special_requests,reservation_status,reservation_status_date
0,Resort Hotel,0,342,2015,July,27,1,0,0,2,...,No Deposit,NaN,NaN,0,Transient,0.00,0,0,Check-Out,2015-07-01
1,Resort Hotel,0,737,2015,July,27,1,0,0,2,...,No Deposit,NaN,NaN,0,Transient,0.00,0,0,Check-Out,2015-07-01
2,Resort Hotel,0,7,2015,July,27,1,0,1,1,...,No Deposit,NaN,NaN,0,Transient,75.00,0,0,Check-Out,2015-07-02
3,Resort Hotel,0,13,2015,July,27,1,0,1,1,...,No Deposit,304.0,NaN,0,Transient,75.00,0,0,Check-Out,2015-07-02
4,Resort Hotel,0,14,2015,July,27,1,0,2,2,...,No Deposit,240.0,NaN,0,Transient,98.00,0,1,Check-Out,2015-07-03
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
119385,City Hotel,0,23,2017,August,35,30,2,5,2,...,No Deposit,394.0,NaN,0,Transient,96.14,0,0,Check-Out,2017-09-06
119386,City Hotel,0,102,2017,August,35,31,2,5,3,...,No Deposit,9.0,NaN,0,Transient,225.43,0,2,Check-Out,2017-09-07
119387,City Hotel,0,34,2017,August,35,31,2,5,2,...,No Deposit,9.0,NaN,0,Transient,157.71,0,4,Check-Out,2017-09-07
119388,City Hotel,0,109,2017,August,35,31,2,5,2,...,No Deposit,89.0,NaN,0,Transient,104.40,0,0,Check-Out,2017-09-07
119389,City Hotel,0,205,2017,August,35,29,2,7,2,...,No Deposit,9.0,NaN,0,Transient,151.20,0,2,Check-Out,2017-09-07

In [43]:
df_copy.dropna()

,hotel,is_canceled,lead_time,arrival_date_year,arrival_date_month,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,...,deposit_type,agent,company,days_in_waiting_list,customer_type,adr,required_car_parking_spaces,total_of_special_requests,reservation_status,reservation_status_date
2392,Resort Hotel,0,6,2015,October,42,11,2,0,2,...,No Deposit,240.0,113.0,0,Transient,82.0,1,1,Check-Out,2015-10-13
2697,Resort Hotel,0,24,2015,October,44,26,7,15,1,...,No Deposit,185.0,281.0,0,Transient-Party,52.2,0,0,Check-Out,2015-11-17
2867,Resort Hotel,0,24,2015,November,45,3,0,3,2,...,No Deposit,334.0,281.0,0,Transient-Party,48.0,0,0,Check-Out,2015-11-06
2877,Resort Hotel,0,24,2015,November,45,3,2,10,1,...,No Deposit,328.0,281.0,0,Transient-Party,40.0,0,0,Check-Out,2015-11-15
2878,Resort Hotel,0,24,2015,November,45,3,3,10,2,...,No Deposit,326.0,281.0,0,Transient-Party,48.0,0,0,Check-Out,2015-11-16
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
112499,City Hotel,0,13,2017,May,21,24,0,1,2,...,No Deposit,9.0,478.0,0,Transient-Party,150.0,0,1,Check-Out,2017-05-25
113046,City Hotel,0,13,2017,May,22,29,1,3,1,...,No Deposit,290.0,148.0,0,Transient,95.0,0,0,Check-Out,2017-06-02
113082,City Hotel,0,13,2017,May,22,29,1,3,2,...,No Deposit,290.0,148.0,0,Transient,110.0,0,0,Check-Out,2017-06-02
113627,City Hotel,0,210,2017,June,23,9,0,1,2,...,No Deposit,14.0,229.0,0,Transient,135.0,0,0,Check-Out,2017-06-10
116451,City Hotel,0,191,2017,July,29,16,2,2,2,...,No Deposit,9.0,421.0,0,Transient,120.6,0,2,Check-Out,2017-07-20

In [44]:
#as we see there is huge data we lost because of missing values so droping the data is not a proper option
#before droping we need to understand the data and drop it. we can replace it.

In [45]:
df.isna().sum()

hotel                                  0
is_canceled                            0
lead_time                              0
arrival_date_year                      0
arrival_date_month                     0
arrival_date_week_number               0
arrival_date_day_of_month              0
stays_in_weekend_nights                0
stays_in_week_nights                   0
adults                                 0
children                               4
babies                                 0
meal                                   0
country                              488
market_segment                         0
distribution_channel                   0
is_repeated_guest                      0
previous_cancellations                 0
previous_bookings_not_canceled         0
reserved_room_type                     0
assigned_room_type                     0
booking_changes                        0
deposit_type                           0
agent                              16340
company                           112593
days_in_waiting_list                   0
customer_type                          0
adr                                    0
required_car_parking_spaces            0
total_of_special_requests              0
reservation_status                     0
reservation_status_date                0
dtype: int64

In [46]:
df.agent.isnull().sum()

16340

In [47]:
df['agent'].unique()

array([ nan, 304., 240., 303.,  15., 241.,   8., 250., 115.,   5., 175.,
       134., 156., 243., 242.,   3., 105.,  40., 147., 306., 184.,  96.,
         2., 127.,  95., 146.,   9., 177.,   6., 143., 244., 149., 167.,
       300., 171., 305.,  67., 196., 152., 142., 261., 104.,  36.,  26.,
        29., 258., 110.,  71., 181.,  88., 251., 275.,  69., 248., 208.,
       256., 314., 126., 281., 273., 253., 185., 330., 334., 328., 326.,
       321., 324., 313.,  38., 155.,  68., 335., 308., 332.,  94., 348.,
       310., 339., 375.,  66., 327., 387., 298.,  91., 245., 385., 257.,
       393., 168., 405., 249., 315.,  75., 128., 307.,  11., 436.,   1.,
       201., 183., 223., 368., 336., 291., 464., 411., 481.,  10., 154.,
       468., 410., 390., 440., 495., 492., 493., 434.,  57., 531., 420.,
       483., 526., 472., 429.,  16., 446.,  34.,  78., 139., 252., 270.,
        47., 114., 301., 193., 182., 135., 350., 195., 352., 355., 159.,
       363., 384., 360., 331., 367.,  64., 406., 163., 414., 333., 427.,
       431., 430., 426., 438., 433., 418., 441., 282., 432.,  72., 450.,
       180., 454., 455.,  59., 451., 254., 358., 469., 165., 467., 510.,
       337., 476., 502., 527., 479., 508., 535., 302., 497., 187.,  13.,
         7.,  27.,  14.,  22.,  17.,  28.,  42.,  20.,  19.,  45.,  37.,
        61.,  39.,  21.,  24.,  41.,  50.,  30.,  54.,  52.,  12.,  44.,
        31.,  83.,  32.,  63.,  60.,  55.,  56.,  89.,  87., 118.,  86.,
        85., 210., 214., 129., 179., 138., 174., 170., 153.,  93., 151.,
       119.,  35., 173.,  58.,  53., 133.,  79., 235., 192., 191., 236.,
       162., 215., 157., 287., 132., 234.,  98.,  77., 103., 107., 262.,
       220., 121., 205., 378.,  23., 296., 290., 229.,  33., 286., 276.,
       425., 484., 323., 403., 219., 394., 509., 111., 423.,   4.,  70.,
        82.,  81.,  74.,  92.,  99.,  90., 112., 117., 106., 148., 158.,
       144., 211., 213., 216., 232., 150., 267., 227., 247., 278., 280.,
       285., 289., 269., 295., 265., 288., 122., 294., 325., 341., 344.,
       346., 359., 283., 364., 370., 371.,  25., 141., 391., 397., 416.,
       404., 299., 197.,  73., 354., 444., 408., 461., 388., 453., 459.,
       474., 475., 480., 449.])

In [48]:
df['agent'].mean()

86.69338185346919

In [49]:
df['agent'].median()

14.0

In [50]:
df['agent'].mode()

0    9.0
Name: agent, dtype: float64

In [51]:
#we can fill those using mean, mode and median and also fill using forward and backward fill methods
df['agent'] = df['agent'].fillna(method='bfill')
df['agent'].isnull().sum()

C:\Users\nachi\AppData\Local\Temp\ipykernel_10400\3628503596.py:2: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df['agent'] = df['agent'].fillna(method='bfill')

0

In [52]:
df['company'].isnull().sum()

112593

In [28]:
df.company.unique()

array([ nan, 110., 113., 270., 178., 240., 154., 144., 307., 268.,  59.,
       204., 312., 318.,  94., 174., 274., 195., 223., 317., 281., 118.,
        53., 286.,  12.,  47., 324., 342., 373., 371., 383.,  86.,  82.,
       218.,  88.,  31., 397., 392., 405., 331., 367.,  20.,  83., 416.,
        51., 395., 102.,  34.,  84., 360., 394., 457., 382., 461., 478.,
       386., 112., 486., 421.,   9., 308., 135., 224., 504., 269., 356.,
       498., 390., 513., 203., 263., 477., 521., 169., 515., 445., 337.,
       251., 428., 292., 388., 130., 250., 355., 254., 543., 531., 528.,
        62., 120.,  42.,  81., 116., 530., 103.,  39.,  16.,  92.,  61.,
       501., 165., 291., 290.,  43., 325., 192., 108., 200., 465., 287.,
       297., 490., 482., 207., 282., 437., 225., 329., 272.,  28.,  77.,
       338.,  72., 246., 319., 146., 159., 380., 323., 511., 407., 278.,
        80., 403., 399.,  14., 137., 343., 346., 347., 349., 289., 351.,
       353.,  54.,  99., 358., 361., 362., 366., 372., 365., 277., 109.,
       377., 379.,  22., 378., 330., 364., 401., 232., 255., 384., 167.,
       212., 514., 391., 400., 376., 402., 396., 302., 398.,   6., 370.,
       369., 409., 168., 104., 408., 413., 148.,  10., 333., 419., 415.,
       424., 425., 423., 422., 435., 439., 442., 448., 443., 454., 444.,
        52., 459., 458., 456., 460., 447., 470., 466., 484., 184., 485.,
        32., 487., 491., 494., 193., 516., 496., 499.,  29.,  78., 520.,
       507., 506., 512., 126.,  64., 242., 518., 523., 539., 534., 436.,
       525., 541.,  40., 455., 410.,  45.,  38.,  49.,  48.,  67.,  68.,
        65.,  91.,  37.,   8., 179., 209., 219., 221., 227., 153., 186.,
       253., 202., 216., 275., 233., 280., 309., 321.,  93., 316.,  85.,
       107., 350., 279., 334., 348., 150.,  73., 385., 418., 197., 450.,
       452., 115.,  46.,  76.,  96., 100., 105., 101., 122.,  11., 139.,
       142., 127., 143., 140., 149., 163., 160., 180., 238., 183., 222.,
       185., 217., 215., 213., 237., 230., 234.,  35., 245., 158., 258.,
       259., 260., 411., 257., 271.,  18., 106., 210., 273.,  71., 284.,
       301., 305., 293., 264., 311., 304., 313., 288., 320., 314., 332.,
       341., 352., 243., 368., 393., 132., 220., 412., 420., 426., 417.,
       429., 433., 446., 357., 479., 483., 489., 229., 481., 497., 451.,
       492.])

In [53]:
df['company'] = df['company'].fillna(df['company'].mean())

In [54]:
df['company']

0         189.266735
1         189.266735
2         189.266735
3         189.266735
4         189.266735
             ...
119385    189.266735
119386    189.266735
119387    189.266735
119388    189.266735
119389    189.266735
Name: company, Length: 119390, dtype: float64

In [55]:
df.isnull().sum()

hotel                               0
is_canceled                         0
lead_time                           0
arrival_date_year                   0
arrival_date_month                  0
arrival_date_week_number            0
arrival_date_day_of_month           0
stays_in_weekend_nights             0
stays_in_week_nights                0
adults                              0
children                            4
babies                              0
meal                                0
country                           488
market_segment                      0
distribution_channel                0
is_repeated_guest                   0
previous_cancellations              0
previous_bookings_not_canceled      0
reserved_room_type                  0
assigned_room_type                  0
booking_changes                     0
deposit_type                        0
agent                               0
company                             0
days_in_waiting_list                0
customer_type                       0
adr                                 0
required_car_parking_spaces         0
total_of_special_requests           0
reservation_status                  0
reservation_status_date             0
dtype: int64

In [56]:
df['country'].value_counts()

country
PRT    48590
GBR    12129
FRA    10415
ESP     8568
DEU     7287
       ...
DJI        1
BWA        1
HND        1
VGB        1
NAM        1
Name: count, Length: 177, dtype: int64

In [57]:
df['country'].unique()

array(['PRT', 'GBR', 'USA', 'ESP', 'IRL', 'FRA', nan, 'ROU', 'NOR', 'OMN',
       'ARG', 'POL', 'DEU', 'BEL', 'CHE', 'CN', 'GRC', 'ITA', 'NLD',
       'DNK', 'RUS', 'SWE', 'AUS', 'EST', 'CZE', 'BRA', 'FIN', 'MOZ',
       'BWA', 'LUX', 'SVN', 'ALB', 'IND', 'CHN', 'MEX', 'MAR', 'UKR',
       'SMR', 'LVA', 'PRI', 'SRB', 'CHL', 'AUT', 'BLR', 'LTU', 'TUR',
       'ZAF', 'AGO', 'ISR', 'CYM', 'ZMB', 'CPV', 'ZWE', 'DZA', 'KOR',
       'CRI', 'HUN', 'ARE', 'TUN', 'JAM', 'HRV', 'HKG', 'IRN', 'GEO',
       'AND', 'GIB', 'URY', 'JEY', 'CAF', 'CYP', 'COL', 'GGY', 'KWT',
       'NGA', 'MDV', 'VEN', 'SVK', 'FJI', 'KAZ', 'PAK', 'IDN', 'LBN',
       'PHL', 'SEN', 'SYC', 'AZE', 'BHR', 'NZL', 'THA', 'DOM', 'MKD',
       'MYS', 'ARM', 'JPN', 'LKA', 'CUB', 'CMR', 'BIH', 'MUS', 'COM',
       'SUR', 'UGA', 'BGR', 'CIV', 'JOR', 'SYR', 'SGP', 'BDI', 'SAU',
       'VNM', 'PLW', 'QAT', 'EGY', 'PER', 'MLT', 'MWI', 'ECU', 'MDG',
       'ISL', 'UZB', 'NPL', 'BHS', 'MAC', 'TGO', 'TWN', 'DJI', 'STP',
       'KNA', 'ETH', 'IRQ', 'HND', 'RWA', 'KHM', 'MCO', 'BGD', 'IMN',
       'TJK', 'NIC', 'BEN', 'VGB', 'TZA', 'GAB', 'GHA', 'TMP', 'GLP',
       'KEN', 'LIE', 'GNB', 'MNE', 'UMI', 'MYT', 'FRO', 'MMR', 'PAN',
       'BFA', 'LBY', 'MLI', 'NAM', 'BOL', 'PRY', 'BRB', 'ABW', 'AIA',
       'SLV', 'DMA', 'PYF', 'GUY', 'LCA', 'ATA', 'GTM', 'ASM', 'MRT',
       'NCL', 'KIR', 'SDN', 'ATF', 'SLE', 'LAO'], dtype=object)

In [58]:
df['country'] = df['company'].fillna(df['country'].mode())
df

,hotel,is_canceled,lead_time,arrival_date_year,arrival_date_month,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,...,deposit_type,agent,company,days_in_waiting_list,customer_type,adr,required_car_parking_spaces,total_of_special_requests,reservation_status,reservation_status_date
0,Resort Hotel,0,342,2015,July,27,1,0,0,2,...,No Deposit,304.0,189.266735,0,Transient,0.00,0,0,Check-Out,2015-07-01
1,Resort Hotel,0,737,2015,July,27,1,0,0,2,...,No Deposit,304.0,189.266735,0,Transient,0.00,0,0,Check-Out,2015-07-01
2,Resort Hotel,0,7,2015,July,27,1,0,1,1,...,No Deposit,304.0,189.266735,0,Transient,75.00,0,0,Check-Out,2015-07-02
3,Resort Hotel,0,13,2015,July,27,1,0,1,1,...,No Deposit,304.0,189.266735,0,Transient,75.00,0,0,Check-Out,2015-07-02
4,Resort Hotel,0,14,2015,July,27,1,0,2,2,...,No Deposit,240.0,189.266735,0,Transient,98.00,0,1,Check-Out,2015-07-03
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
119385,City Hotel,0,23,2017,August,35,30,2,5,2,...,No Deposit,394.0,189.266735,0,Transient,96.14,0,0,Check-Out,2017-09-06
119386,City Hotel,0,102,2017,August,35,31,2,5,3,...,No Deposit,9.0,189.266735,0,Transient,225.43,0,2,Check-Out,2017-09-07
119387,City Hotel,0,34,2017,August,35,31,2,5,2,...,No Deposit,9.0,189.266735,0,Transient,157.71,0,4,Check-Out,2017-09-07
119388,City Hotel,0,109,2017,August,35,31,2,5,2,...,No Deposit,89.0,189.266735,0,Transient,104.40,0,0,Check-Out,2017-09-07
119389,City Hotel,0,205,2017,August,35,29,2,7,2,...,No Deposit,9.0,189.266735,0,Transient,151.20,0,2,Check-Out,2017-09-07

In [59]:
df.isnull().sum()

hotel                             0
is_canceled                       0
lead_time                         0
arrival_date_year                 0
arrival_date_month                0
arrival_date_week_number          0
arrival_date_day_of_month         0
stays_in_weekend_nights           0
stays_in_week_nights              0
adults                            0
children                          4
babies                            0
meal                              0
country                           0
market_segment                    0
distribution_channel              0
is_repeated_guest                 0
previous_cancellations            0
previous_bookings_not_canceled    0
reserved_room_type                0
assigned_room_type                0
booking_changes                   0
deposit_type                      0
agent                             0
company                           0
days_in_waiting_list              0
customer_type                     0
adr                               0
required_car_parking_spaces       0
total_of_special_requests         0
reservation_status                0
reservation_status_date           0
dtype: int64

In [61]:
#to change the dtype of any column
#first know the data types 
df.dtypes

hotel                              object
is_canceled                         int64
lead_time                           int64
arrival_date_year                   int64
arrival_date_month                 object
arrival_date_week_number            int64
arrival_date_day_of_month           int64
stays_in_weekend_nights             int64
stays_in_week_nights                int64
adults                              int64
children                          float64
babies                              int64
meal                               object
country                           float64
market_segment                     object
distribution_channel               object
is_repeated_guest                   int64
previous_cancellations              int64
previous_bookings_not_canceled      int64
reserved_room_type                 object
assigned_room_type                 object
booking_changes                     int64
deposit_type                       object
agent                             float64
company                           float64
days_in_waiting_list                int64
customer_type                      object
adr                               float64
required_car_parking_spaces         int64
total_of_special_requests           int64
reservation_status                 object
reservation_status_date            object
dtype: object

In [62]:
df.head()

,hotel,is_canceled,lead_time,arrival_date_year,arrival_date_month,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,...,deposit_type,agent,company,days_in_waiting_list,customer_type,adr,required_car_parking_spaces,total_of_special_requests,reservation_status,reservation_status_date
0,Resort Hotel,0,342,2015,July,27,1,0,0,2,...,No Deposit,304.0,189.266735,0,Transient,0.0,0,0,Check-Out,2015-07-01
1,Resort Hotel,0,737,2015,July,27,1,0,0,2,...,No Deposit,304.0,189.266735,0,Transient,0.0,0,0,Check-Out,2015-07-01
2,Resort Hotel,0,7,2015,July,27,1,0,1,1,...,No Deposit,304.0,189.266735,0,Transient,75.0,0,0,Check-Out,2015-07-02
3,Resort Hotel,0,13,2015,July,27,1,0,1,1,...,No Deposit,304.0,189.266735,0,Transient,75.0,0,0,Check-Out,2015-07-02
4,Resort Hotel,0,14,2015,July,27,1,0,2,2,...,No Deposit,240.0,189.266735,0,Transient,98.0,0,1,Check-Out,2015-07-03

In [63]:
#replace the values 
df_copy

,hotel,is_canceled,lead_time,arrival_date_year,arrival_date_month,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,...,deposit_type,agent,company,days_in_waiting_list,customer_type,adr,required_car_parking_spaces,total_of_special_requests,reservation_status,reservation_status_date
0,Resort Hotel,0,342,2015,July,27,1,0,0,2,...,No Deposit,304.0,189.266735,0,Transient,0.00,0,0,Check-Out,2015-07-01
1,Resort Hotel,0,737,2015,July,27,1,0,0,2,...,No Deposit,304.0,189.266735,0,Transient,0.00,0,0,Check-Out,2015-07-01
2,Resort Hotel,0,7,2015,July,27,1,0,1,1,...,No Deposit,304.0,189.266735,0,Transient,75.00,0,0,Check-Out,2015-07-02
3,Resort Hotel,0,13,2015,July,27,1,0,1,1,...,No Deposit,304.0,189.266735,0,Transient,75.00,0,0,Check-Out,2015-07-02
4,Resort Hotel,0,14,2015,July,27,1,0,2,2,...,No Deposit,240.0,189.266735,0,Transient,98.00,0,1,Check-Out,2015-07-03
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
119385,City Hotel,0,23,2017,August,35,30,2,5,2,...,No Deposit,394.0,189.266735,0,Transient,96.14,0,0,Check-Out,2017-09-06
119386,City Hotel,0,102,2017,August,35,31,2,5,3,...,No Deposit,9.0,189.266735,0,Transient,225.43,0,2,Check-Out,2017-09-07
119387,City Hotel,0,34,2017,August,35,31,2,5,2,...,No Deposit,9.0,189.266735,0,Transient,157.71,0,4,Check-Out,2017-09-07
119388,City Hotel,0,109,2017,August,35,31,2,5,2,...,No Deposit,89.0,189.266735,0,Transient,104.40,0,0,Check-Out,2017-09-07
119389,City Hotel,0,205,2017,August,35,29,2,7,2,...,No Deposit,9.0,189.266735,0,Transient,151.20,0,2,Check-Out,2017-09-07

In [67]:
a = {
    'Name':['alice','bob','charlie','david','emma'],
    'Age':[25,30,35,40,22],
    'Score':[88,92,79,85,95]}
b = pd.DataFrame(data=a)
b

      Name  Age  Score
0    alice   25     88
1      bob   30     92
2  charlie   35     79
3    david   40     85
4     emma   22     95

In [68]:
b['Score'] = b['Score'].astype(float) #to change dtype of any column

In [69]:
b

      Name  Age  Score
0    alice   25   88.0
1      bob   30   92.0
2  charlie   35   79.0
3    david   40   85.0
4     emma   22   95.0

In [70]:
#to replace
b['Name'] = b['Name'].replace('bob', 'Robert')

In [71]:
b['Name']

0      alice
1     Robert
2    charlie
3      david
4       emma
Name: Name, dtype: object

In [72]:
b['Score'] = b['Score'].replace({88.0:90.0, 95.0:99.0}) #for changing multiple values

In [73]:
b

      Name  Age  Score
0    alice   25   90.0
1   Robert   30   92.0
2  charlie   35   79.0
3    david   40   85.0
4     emma   22   99.0

In [74]:
b.dtypes

Name      object
Age        int64
Score    float64
dtype: object

In [75]:
#dropping row and columns
c = b

In [ ]:
#c.drop(labels, axis)
c.drop(['Name'], axis=1) #axis 1 is for column , we not used implace =treu hence it nor permanent

   Age  Score
0   25   90.0
1   30   92.0
2   35   79.0
3   40   85.0
4   22   99.0

In [79]:
c.drop(1, axis=0, inplace=True)

In [81]:
c.drop(3, inplace=True) #bydefault axis is 0

In [82]:
c

      Name  Age  Score
0    alice   25   90.0
2  charlie   35   79.0
4     emma   22   99.0

In [83]:
#deleting and removing duplicates
data = {
    'Name':['alice','bob','charlie','alice', 'bob','david'],
    'age':[25,30,35,34,30,40],
    'score':[88,92,79,88,92,95]
}
df = pd.DataFrame(data)

In [85]:
df.duplicated() #all the row must have same values then only it considered as duplicated if one value also changed then it not

0    False
1    False
2    False
3    False
4     True
5    False
dtype: bool

In [86]:
df.drop_duplicates(inplace=True)
df

      Name  age  score
0    alice   25     88
1      bob   30     92
2  charlie   35     79
3    alice   34     88
5    david   40     95

In [147]:
import pandas as pd
import numpy as np

# 1. Create a messy DataFrame
data = {
    "Name": ["Alice", "Bob", "Chrlie", "David", "Alice", None],
    "Age": ["25", "30", None, "40", "25", "30"],      # ages stored as strings, with missing value
    "City": ["Delhi", "Mumbai", "Pun", "Bangalore", "Delhi", "Mumbai"],  # typo: "Pun" -> "Pune"
    "Score": [85, None, 78, 88, 85, 91],              # missing value in Score
    "Extra": ["x", "y", "z", "x", "y", "z"]           # extra column we don't really need
}

df = pd.DataFrame(data)

print("Original messy DataFrame:")
print(df)

# 2. Handle missing values
# Fill or drop as needed

# 3. Change data types
# Convert Age to int, Score to float, etc.

# 4. Replace incorrect values
# Fix 'Pun' -> 'Pune', maybe unify Name spellings if needed

# 5. Drop unnecessary rows/columns
# Remove 'Extra' or any row you don't want

# 6. Remove duplicates
# Use duplicated() and drop_duplicates()

# 7. Final clean DataFrame
# Print the cleaned DataFrame and check info()

Original messy DataFrame:
     Name   Age       City  Score Extra
0   Alice    25      Delhi   85.0     x
1     Bob    30     Mumbai    NaN     y
2  Chrlie  None        Pun   78.0     z
3   David    40  Bangalore   88.0     x
4   Alice    25      Delhi   85.0     y
5    None    30     Mumbai   91.0     z

In [148]:
#2handle missing values 
df.isnull().sum()

Name     1
Age      1
City     0
Score    1
Extra    0
dtype: int64

In [149]:
df.drop(5, inplace=True)
df

     Name   Age       City  Score Extra
0   Alice    25      Delhi   85.0     x
1     Bob    30     Mumbai    NaN     y
2  Chrlie  None        Pun   78.0     z
3   David    40  Bangalore   88.0     x
4   Alice    25      Delhi   85.0     y

In [150]:
print(df['Age'].dtype)
df['Age'] = df['Age'].astype('Int32')
print(df['Age'].dtype)
print(df['Age'])

object
Int32
0      25
1      30
2    <NA>
3      40
4      25
Name: Age, dtype: Int32

In [151]:
df['Age'] = df['Age'].fillna(df['Age'].mean())

In [152]:
df['Age']

0    25
1    30
2    30
3    40
4    25
Name: Age, dtype: Int32

In [153]:
df['Score']

0    85.0
1     NaN
2    78.0
3    88.0
4    85.0
Name: Score, dtype: float64

In [154]:
df['Score'] = df['Score'].fillna(df['Score'].mean())

In [155]:
df

     Name  Age       City  Score Extra
0   Alice   25      Delhi   85.0     x
1     Bob   30     Mumbai   84.0     y
2  Chrlie   30        Pun   78.0     z
3   David   40  Bangalore   88.0     x
4   Alice   25      Delhi   85.0     y

In [156]:
#replace values 
df

     Name  Age       City  Score Extra
0   Alice   25      Delhi   85.0     x
1     Bob   30     Mumbai   84.0     y
2  Chrlie   30        Pun   78.0     z
3   David   40  Bangalore   88.0     x
4   Alice   25      Delhi   85.0     y

In [157]:
df['City'] = df['City'].replace('Pun','Pune')

In [158]:
df

     Name  Age       City  Score Extra
0   Alice   25      Delhi   85.0     x
1     Bob   30     Mumbai   84.0     y
2  Chrlie   30       Pune   78.0     z
3   David   40  Bangalore   88.0     x
4   Alice   25      Delhi   85.0     y

In [159]:
df.duplicated()

0    False
1    False
2    False
3    False
4    False
dtype: bool

In [161]:
df.drop('Extra', axis=1, inplace=True)

In [162]:
df

     Name  Age       City  Score
0   Alice   25      Delhi   85.0
1     Bob   30     Mumbai   84.0
2  Chrlie   30       Pune   78.0
3   David   40  Bangalore   88.0
4   Alice   25      Delhi   85.0

In [163]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    5 non-null      object
 1   Age     5 non-null      Int32
 2   City    5 non-null      object
 3   Score   5 non-null      float64
dtypes: Int32(1), float64(1), object(2)
memory usage: 277.0+ bytes