In [1]:
#data selection and filtering
#boolean indexing and conditional selection 
'''use comparison operators to build conditions
pass the condition inside df[..] to get matching rows
combine multiple conditions with & (and) | (or) and ~ (not).
parentheses are required when combining conditions'''

In [2]:
import pandas as pd
import numpy as np
data = {
    "Name": ["Alice", "Bob", "Chrlie", "David", "Ali", None],
    "Age": ["25", "30", None, "40", "25", "30"],     
    "City": ["Delhi", "Mumbai", "Pune", "Bangalore", "Delhi", "Mumbai"],  
    "Score": [85, None, 78, 88, 85, 91],             
}
df = pd.DataFrame(data)

In [6]:
df['Age'] = df['Age'].astype('Int64')

In [7]:
df['Age']>30

0    False
1    False
2     <NA>
3     True
4    False
5    False
Name: Age, dtype: boolean

In [9]:
df[df['Age']>30]

    Name  Age       City  Score
3  David   40  Bangalore   88.0

In [10]:
df[(df['Age']>25)&(df['Score']>80)]

    Name  Age       City  Score
3  David   40  Bangalore   88.0
5   None   30     Mumbai   91.0

In [11]:
df[(df['Name'].str.startswith('A') | (df['City'].str.startswith('B')))]

    Name  Age       City  Score
0  Alice   25      Delhi   85.0
3  David   40  Bangalore   88.0
4    Ali   25      Delhi   85.0

In [15]:
df[(df['Score']>85)]

    Name  Age       City  Score
3  David   40  Bangalore   88.0
5   None   30     Mumbai   91.0

In [16]:
df[~(df['Score']>85)]

     Name   Age    City  Score
0   Alice    25   Delhi   85.0
1     Bob    30  Mumbai    NaN
2  Chrlie  <NA>    Pune   78.0
4     Ali    25   Delhi   85.0

In [18]:
#using query() for cleaner filtering
'''query() allows filtering rows with a string expression
it;s concise and readable for complex conditions
variables can be passed using the @ symbol
'''
#simple query : age>25
df.query('Age>25')

C:\Users\nachi\AppData\Local\Temp\ipykernel_17052\3543605315.py:7: RuntimeWarning: Engine has switched to 'python' because numexpr does not support extension array dtypes. Please set your engine to python manually.
  df.query('Age>25')

    Name  Age       City  Score
1    Bob   30     Mumbai    NaN
3  David   40  Bangalore   88.0
5   None   30     Mumbai   91.0

In [21]:
df.query("Score>60")

     Name   Age       City  Score
0   Alice    25      Delhi   85.0
2  Chrlie  <NA>       Pune   78.0
3   David    40  Bangalore   88.0
4     Ali    25      Delhi   85.0
5    None    30     Mumbai   91.0

In [22]:
#multiple condition with query()
df.query("Age<35 & Score<90")

C:\Users\nachi\AppData\Local\Temp\ipykernel_17052\3788967995.py:2: RuntimeWarning: Engine has switched to 'python' because numexpr does not support extension array dtypes. Please set your engine to python manually.
  df.query("Age<35 & Score<90")

    Name  Age   City  Score
0  Alice   25  Delhi   85.0
4    Ali   25  Delhi   85.0

In [27]:
df.query("Age>30 | City=='Delhi'")

C:\Users\nachi\AppData\Local\Temp\ipykernel_17052\3801652424.py:1: RuntimeWarning: Engine has switched to 'python' because numexpr does not support extension array dtypes. Please set your engine to python manually.
  df.query("Age>30 | City=='Delhi'")

    Name  Age       City  Score
0  Alice   25      Delhi   85.0
3  David   40  Bangalore   88.0
4    Ali   25      Delhi   85.0

In [28]:
df.query("Age>30 or City=='Delhi'")

C:\Users\nachi\AppData\Local\Temp\ipykernel_17052\915606313.py:1: RuntimeWarning: Engine has switched to 'python' because numexpr does not support extension array dtypes. Please set your engine to python manually.
  df.query("Age>30 or City=='Delhi'")

    Name  Age       City  Score
0  Alice   25      Delhi   85.0
3  David   40  Bangalore   88.0
4    Ali   25      Delhi   85.0

In [30]:
hold = 90
df.query("Score >@hold") #we can use variable using @ in query

   Name  Age    City  Score
5  None   30  Mumbai   91.0

In [31]:
df['Name'].str.lower()

0     alice
1       bob
2    chrlie
3     david
4       ali
5      None
Name: Name, dtype: object

In [33]:
df['City'].str.upper()

0        DELHI
1       MUMBAI
2         PUNE
3    BANGALORE
4        DELHI
5       MUMBAI
Name: City, dtype: object

In [40]:
df['Name'].str.contains("A", case=False) #case false avoid upper and lower case

0     True
1    False
2    False
3     True
4     True
5     None
Name: Name, dtype: object

In [42]:
df['Name'].str.replace('Chrlie','chars')

0    Alice
1      Bob
2    chars
3    David
4      Ali
5     None
Name: Name, dtype: object

In [47]:
df[df['Name'].str.endswith('i', na=False)]

  Name  Age   City  Score
4  Ali   25  Delhi   85.0

In [ ]:
'''Mini Practice
Build a DataFrame with columns such as Name, Age, City, Score.
Use boolean indexing to select rows where Age > 25.
Filter rows where City is either 'Delhi' or 'Mumbai'.
Use query() to find rows with Score >= 85 and Age < 35.
Clean a text column using str.replace or str.lower.'''

In [50]:
df['Age']>25

0    False
1     True
2     <NA>
3     True
4    False
5     True
Name: Age, dtype: boolean

In [51]:
df[(df['City']=='Delhi') | (df['City']=='Mumbai')]

    Name  Age    City  Score
0  Alice   25   Delhi   85.0
1    Bob   30  Mumbai    NaN
4    Ali   25   Delhi   85.0
5   None   30  Mumbai   91.0

In [52]:
df.query("Score>=85 and Age<35")

C:\Users\nachi\AppData\Local\Temp\ipykernel_17052\711930606.py:1: RuntimeWarning: Engine has switched to 'python' because numexpr does not support extension array dtypes. Please set your engine to python manually.
  df.query("Score>=85 and Age<35")

    Name  Age    City  Score
0  Alice   25   Delhi   85.0
4    Ali   25   Delhi   85.0
5   None   30  Mumbai   91.0

In [53]:
print(df['Name'].str.upper())

0     ALICE
1       BOB
2    CHRLIE
3     DAVID
4       ALI
5      None
Name: Name, dtype: object