In [1]:
import pandas as pd

# New dataset: Employees, their Department, and Salary
data = {
    "Employee": ["John", "Sarah", "Mike", "Anna", "Tom", "Laura", "Steve", "Kate"],
    "Department": ["HR", "IT", "IT", "Finance", "Finance", "HR", "IT", "Finance"],
    "Salary": [50000, 70000, 72000, 65000, 60000, 52000, 75000, 58000]
}

df = pd.DataFrame(data)
print("Original DataFrame:")
print(df)

Original DataFrame:
  Employee Department  Salary
0     John         HR   50000
1    Sarah         IT   70000
2     Mike         IT   72000
3     Anna    Finance   65000
4      Tom    Finance   60000
5    Laura         HR   52000
6    Steve         IT   75000
7     Kate    Finance   58000

In [2]:
df

  Employee Department  Salary
0     John         HR   50000
1    Sarah         IT   70000
2     Mike         IT   72000
3     Anna    Finance   65000
4      Tom    Finance   60000
5    Laura         HR   52000
6    Steve         IT   75000
7     Kate    Finance   58000

In [4]:
df['Department'].value_counts()

Department
IT         3
Finance    3
HR         2
Name: count, dtype: int64

In [12]:
#what is the average salary of each department
#to solve this question if we do manually
print(df[(df['Department']=='IT')]['Salary'].mean())
print(df[df['Department'] =='HR'].Salary.mean())
print(df[(df['Department'] =='Finance')]['Salary'].mean())

72333.33333333333
51000.0
61000.0

In [16]:
#it's too length to avoid this we have a funtion in pandas called groupby
df.groupby('Department')['Salary'] #without aggregation we only get the object with aggregation we get actual values

In [17]:
df.groupby('Department')['Salary'].mean()

Department
Finance    61000.000000
HR         51000.000000
IT         72333.333333
Name: Salary, dtype: float64

In [18]:
df.groupby('Department')['Employee'].count()

Department
Finance    3
HR         2
IT         3
Name: Employee, dtype: int64

In [ ]:
df.groupby('Department')['Salary'].agg(['mean','count','min','max','std'])
#when we want multiple aggragation function we we agg and provide function in list

                    mean  count    min    max          std
Department
Finance     61000.000000      3  58000  65000  3605.551275
HR          51000.000000      2  50000  52000  1414.213562
IT          72333.333333      3  70000  75000  2516.611478

In [21]:
#multiple aggregations on different columns
import pandas as pd

# Same dataset
data = {
    "Employee": ["John", "Sarah", "Mike", "Anna", "Tom", "Laura", "Steve", "Kate"],
    "Department": ["HR", "IT", "IT", "Finance", "Finance", "HR", "IT", "Finance"],
    "Salary": [50000, 70000, 72000, 65000, 60000, 52000, 75000, 58000],
    "Age": [28, 32, 30, 27, 35, 29, 31, 26]
}

df = pd.DataFrame(data)
print("Original DataFrame:")
print(df)

Original DataFrame:
  Employee Department  Salary  Age
0     John         HR   50000   28
1    Sarah         IT   70000   32
2     Mike         IT   72000   30
3     Anna    Finance   65000   27
4      Tom    Finance   60000   35
5    Laura         HR   52000   29
6    Steve         IT   75000   31
7     Kate    Finance   58000   26

In [22]:
df

  Employee Department  Salary  Age
0     John         HR   50000   28
1    Sarah         IT   70000   32
2     Mike         IT   72000   30
3     Anna    Finance   65000   27
4      Tom    Finance   60000   35
5    Laura         HR   52000   29
6    Steve         IT   75000   31
7     Kate    Finance   58000   26

In [23]:
df.groupby('Department').agg({
    'Salary':['mean','max','min'],
    'Age':['mean','max'],
    
})

                  Salary                      Age
                    mean    max    min       mean max
Department
Finance     61000.000000  65000  58000  29.333333  35
HR          51000.000000  52000  50000  28.500000  29
IT          72333.333333  75000  70000  31.000000  32

In [24]:
#pivot tables and cross tab
'''pivot table() summarizes data like excel pivot tables
crosstab() shows frequency counts of comninations of factors
both are powerful for summarizing and comparing groups'''
df

  Employee Department  Salary  Age
0     John         HR   50000   28
1    Sarah         IT   70000   32
2     Mike         IT   72000   30
3     Anna    Finance   65000   27
4      Tom    Finance   60000   35
5    Laura         HR   52000   29
6    Steve         IT   75000   31
7     Kate    Finance   58000   26

In [25]:
df.pivot_table(values='Salary', index='Department')

                  Salary
Department
Finance     61000.000000
HR          51000.000000
IT          72333.333333

In [26]:
df.pivot_table(values='Salary', index='Department', aggfunc='mean')

                  Salary
Department
Finance     61000.000000
HR          51000.000000
IT          72333.333333

In [27]:
df.pivot_table(values='Salary', index='Department', aggfunc='sum')

            Salary
Department
Finance     183000
HR          102000
IT          217000

In [29]:
df.pivot_table(values=['Salary','Age'], index='Department',aggfunc=['sum','mean','max'] )

           sum               mean               max
           Age  Salary        Age        Salary Age Salary
Department
Finance     88  183000  29.333333  61000.000000  35  65000
HR          57  102000  28.500000  51000.000000  29  52000
IT          93  217000  31.000000  72333.333333  32  75000

In [33]:
import seaborn as sns
df2 = sns.load_dataset('flights')
df2

     year month  passengers
0    1949   Jan         112
1    1949   Feb         118
2    1949   Mar         132
3    1949   Apr         129
4    1949   May         121
..    ...   ...         ...
139  1960   Aug         606
140  1960   Sep         508
141  1960   Oct         461
142  1960   Nov         390
143  1960   Dec         432

[144 rows x 3 columns]

In [34]:
df2['year'].value_counts()

year
1949    12
1950    12
1951    12
1952    12
1953    12
1954    12
1955    12
1956    12
1957    12
1958    12
1959    12
1960    12
Name: count, dtype: int64

In [35]:
df2.pivot_table(values='passengers', index='year', columns='month')

C:\Users\nachi\AppData\Local\Temp\ipykernel_11308\2940547151.py:1: FutureWarning: The default value of observed=False is deprecated and will change to observed=True in a future version of pandas. Specify observed=False to silence this warning and retain the current behavior
  df2.pivot_table(values='passengers', index='year', columns='month')

month,Jan,Feb,Mar,Apr,May,Jun,Jul,Aug,Sep,Oct,Nov,Dec
year,,,,,,,,,,,,
1949,112.0,118.0,132.0,129.0,121.0,135.0,148.0,148.0,136.0,119.0,104.0,118.0
1950,115.0,126.0,141.0,135.0,125.0,149.0,170.0,170.0,158.0,133.0,114.0,140.0
1951,145.0,150.0,178.0,163.0,172.0,178.0,199.0,199.0,184.0,162.0,146.0,166.0
1952,171.0,180.0,193.0,181.0,183.0,218.0,230.0,242.0,209.0,191.0,172.0,194.0
1953,196.0,196.0,236.0,235.0,229.0,243.0,264.0,272.0,237.0,211.0,180.0,201.0
1954,204.0,188.0,235.0,227.0,234.0,264.0,302.0,293.0,259.0,229.0,203.0,229.0
1955,242.0,233.0,267.0,269.0,270.0,315.0,364.0,347.0,312.0,274.0,237.0,278.0
1956,284.0,277.0,317.0,313.0,318.0,374.0,413.0,405.0,355.0,306.0,271.0,306.0
1957,315.0,301.0,356.0,348.0,355.0,422.0,465.0,467.0,404.0,347.0,305.0,336.0
1958,340.0,318.0,362.0,348.0,363.0,435.0,491.0,505.0,404.0,359.0,310.0,337.0
1959,360.0,342.0,406.0,396.0,420.0,472.0,548.0,559.0,463.0,407.0,362.0,405.0
1960,417.0,391.0,419.0,461.0,472.0,535.0,622.0,606.0,508.0,461.0,390.0,432.0

In [36]:
df2.pivot_table(values='passengers', index='year', columns='month', aggfunc=['mean','count'])

C:\Users\nachi\AppData\Local\Temp\ipykernel_11308\2207346365.py:1: FutureWarning: The default value of observed=False is deprecated and will change to observed=True in a future version of pandas. Specify observed=False to silence this warning and retain the current behavior
  df2.pivot_table(values='passengers', index='year', columns='month', aggfunc=['mean','count'])
C:\Users\nachi\AppData\Local\Temp\ipykernel_11308\2207346365.py:1: FutureWarning: The default value of observed=False is deprecated and will change to observed=True in a future version of pandas. Specify observed=False to silence this warning and retain the current behavior
  df2.pivot_table(values='passengers', index='year', columns='month', aggfunc=['mean','count'])

        mean                                                                 \
month    Jan    Feb    Mar    Apr    May    Jun    Jul    Aug    Sep    Oct
year
1949   112.0  118.0  132.0  129.0  121.0  135.0  148.0  148.0  136.0  119.0
1950   115.0  126.0  141.0  135.0  125.0  149.0  170.0  170.0  158.0  133.0
1951   145.0  150.0  178.0  163.0  172.0  178.0  199.0  199.0  184.0  162.0
1952   171.0  180.0  193.0  181.0  183.0  218.0  230.0  242.0  209.0  191.0
1953   196.0  196.0  236.0  235.0  229.0  243.0  264.0  272.0  237.0  211.0
1954   204.0  188.0  235.0  227.0  234.0  264.0  302.0  293.0  259.0  229.0
1955   242.0  233.0  267.0  269.0  270.0  315.0  364.0  347.0  312.0  274.0
1956   284.0  277.0  317.0  313.0  318.0  374.0  413.0  405.0  355.0  306.0
1957   315.0  301.0  356.0  348.0  355.0  422.0  465.0  467.0  404.0  347.0
1958   340.0  318.0  362.0  348.0  363.0  435.0  491.0  505.0  404.0  359.0
1959   360.0  342.0  406.0  396.0  420.0  472.0  548.0  559.0  463.0  407.0
1960   417.0  391.0  419.0  461.0  472.0  535.0  622.0  606.0  508.0  461.0

       ... count
month  ...   Mar Apr May Jun Jul Aug Sep Oct Nov Dec
year   ...
1949   ...     1   1   1   1   1   1   1   1   1   1
1950   ...     1   1   1   1   1   1   1   1   1   1
1951   ...     1   1   1   1   1   1   1   1   1   1
1952   ...     1   1   1   1   1   1   1   1   1   1
1953   ...     1   1   1   1   1   1   1   1   1   1
1954   ...     1   1   1   1   1   1   1   1   1   1
1955   ...     1   1   1   1   1   1   1   1   1   1
1956   ...     1   1   1   1   1   1   1   1   1   1
1957   ...     1   1   1   1   1   1   1   1   1   1
1958   ...     1   1   1   1   1   1   1   1   1   1
1959   ...     1   1   1   1   1   1   1   1   1   1
1960   ...     1   1   1   1   1   1   1   1   1   1

[12 rows x 24 columns]

In [37]:
df

  Employee Department  Salary  Age
0     John         HR   50000   28
1    Sarah         IT   70000   32
2     Mike         IT   72000   30
3     Anna    Finance   65000   27
4      Tom    Finance   60000   35
5    Laura         HR   52000   29
6    Steve         IT   75000   31
7     Kate    Finance   58000   26

In [38]:
df['Age_group'] = pd.cut(df['Age'], bins=[25,30,35,40],labels=['25-30','31-35','36-40']) #pd.cut used to make new columns

In [39]:
df

  Employee Department  Salary  Age Age_group
0     John         HR   50000   28     25-30
1    Sarah         IT   70000   32     31-35
2     Mike         IT   72000   30     25-30
3     Anna    Finance   65000   27     25-30
4      Tom    Finance   60000   35     31-35
5    Laura         HR   52000   29     25-30
6    Steve         IT   75000   31     31-35
7     Kate    Finance   58000   26     25-30

In [40]:
pd.crosstab(df['Department'], df['Age_group'])

Age_group   25-30  31-35
Department
Finance         2      1
HR              2      0
IT              1      2

In [41]:
'''Mini Practice
Create a DataFrame with columns: Department, Employee, Salary, Age, City.
Group by Department to get average Salary and max Age.
Apply multiple aggregations using agg().
Create a pivot_table to see mean Salary by Department and City.
Build a crosstab for Department vs City.'''

'Mini Practice\nCreate a DataFrame with columns: Department, Employee, Salary, Age, City.\nGroup by Department to get average Salary and max Age.\nApply multiple aggregations using agg().\nCreate a pivot_table to see mean Salary by Department and City.\nBuild a crosstab for Department vs City.'

In [42]:
#multiple aggregations on different columns
import pandas as pd

# Same dataset
data = {
    "Employee": ["John", "Sarah", "Mike", "Anna", "Tom", "Laura", "Steve", "Kate"],
    "Department": ["HR", "IT", "IT", "Finance", "Finance", "HR", "IT", "Finance"],
    "Salary": [50000, 70000, 72000, 65000, 60000, 52000, 75000, 58000],
    "Age": [28, 32, 30, 27, 35, 29, 31, 26],
    'Cities':['mumbai','dehli','pune','raipur','mumbai','pune','pune','surat']
}

df = pd.DataFrame(data)
print("Original DataFrame:")
print(df)

Original DataFrame:
  Employee Department  Salary  Age  Cities
0     John         HR   50000   28  mumbai
1    Sarah         IT   70000   32   dehli
2     Mike         IT   72000   30    pune
3     Anna    Finance   65000   27  raipur
4      Tom    Finance   60000   35  mumbai
5    Laura         HR   52000   29    pune
6    Steve         IT   75000   31    pune
7     Kate    Finance   58000   26   surat

In [43]:
df

  Employee Department  Salary  Age  Cities
0     John         HR   50000   28  mumbai
1    Sarah         IT   70000   32   dehli
2     Mike         IT   72000   30    pune
3     Anna    Finance   65000   27  raipur
4      Tom    Finance   60000   35  mumbai
5    Laura         HR   52000   29    pune
6    Steve         IT   75000   31    pune
7     Kate    Finance   58000   26   surat

In [44]:
df.groupby('Department').agg({
    'Salary':['mean'],
    'Age':'max'
})

                  Salary Age
                    mean max
Department
Finance     61000.000000  35
HR          51000.000000  29
IT          72333.333333  32

In [46]:
df.groupby('Cities')['Salary'].agg(['max','min','mean', 'count'])

          max    min          mean  count
Cities
dehli   70000  70000  70000.000000      1
mumbai  60000  50000  55000.000000      2
pune    75000  52000  66333.333333      3
raipur  65000  65000  65000.000000      1
surat   58000  58000  58000.000000      1

In [48]:
df.pivot_table(values=['Salary'], columns=['Department','Cities'],aggfunc=['mean'])

               mean
Department  Finance                         HR                IT
Cities       mumbai   raipur    surat   mumbai     pune    dehli     pune
Salary      60000.0  65000.0  58000.0  50000.0  52000.0  70000.0  73500.0

In [50]:
pd.crosstab(df['Department'], df['Cities'])

Cities      dehli  mumbai  pune  raipur  surat
Department
Finance         0       1     0       1      1
HR              0       1     1       0      0
IT              1       0     2       0      0