In [2]:
import pandas as pd

In [3]:
'''
1.using concat() for stacking data
* pd.concate() combine dataframes vertically or horizontally
use axis=0 for vertical stacking default, axis=1 for horizontal.
ignore_index = true can reset the index after concatenation'''
df1 = pd.DataFrame({
    "ProductID" : [101,102,103],
    "product name": ["pen", "notebook",'marker'],
    'price':[10,50,30]
})
df2 = pd.DataFrame({
    'ProductID' : [104,105],
    'product name':['pencil','eraser'],
    'price':[5,8]
})
df3 = pd.DataFrame({
    'stock':[100,60,80],
    'rating':[4.5,4.7,4.8]
})

In [9]:
print(df1)
print(df2)
print(df3)

   ProductID product name  price
0        101          pen     10
1        102     notebook     50
2        103       marker     30
   ProductID product name  price
0        104       pencil      5
1        105       eraser      8
   stock  rating
0    100     4.5
1     60     4.7
2     80     4.8

In [4]:
pd.concat([df1,df2])

   ProductID product name  price
0        101          pen     10
1        102     notebook     50
2        103       marker     30
0        104       pencil      5
1        105       eraser      8

In [5]:
pd.concat([df1,df2],ignore_index=True)

   ProductID product name  price
0        101          pen     10
1        102     notebook     50
2        103       marker     30
3        104       pencil      5
4        105       eraser      8

In [6]:
pd.concat([df1,df3]) #get nan when we have unsimilar data

   ProductID product name  price  stock  rating
0      101.0          pen   10.0    NaN     NaN
1      102.0     notebook   50.0    NaN     NaN
2      103.0       marker   30.0    NaN     NaN
0        NaN          NaN    NaN  100.0     4.5
1        NaN          NaN    NaN   60.0     4.7
2        NaN          NaN    NaN   80.0     4.8

In [10]:
pd.concat([df1,df3], axis=1) #concate horizantally, hence not get nan

   ProductID product name  price  stock  rating
0        101          pen     10    100     4.5
1        102     notebook     50     60     4.7
2        103       marker     30     80     4.8

In [15]:
''' 
using merge() for SQL-style joins
* merge() is similar to sql joins
* specify on or left_on/right_on to choose key columns
* join types: inner default, left, right, outer'''
products = pd.concat([df1,df2], ignore_index=True)
products

   ProductID product name  price
0        101          pen     10
1        102     notebook     50
2        103       marker     30
3        104       pencil      5
4        105       eraser      8

In [16]:
sales = pd.DataFrame({
    'ProductID': [101,102,104,106], #106 doesnt exist in products
    'UnitsSold':[500,200,150,50]
})

In [ ]:
pd.merge(products, sales) #gives only present values

   ProductID product name  price  UnitsSold
0        101          pen     10        500
1        102     notebook     50        200
2        104       pencil      5        150

In [18]:
pd.merge(products, sales, on='ProductID')

   ProductID product name  price  UnitsSold
0        101          pen     10        500
1        102     notebook     50        200
2        104       pencil      5        150

In [19]:
pd.merge(products,sales, how='left')

   ProductID product name  price  UnitsSold
0        101          pen     10      500.0
1        102     notebook     50      200.0
2        103       marker     30        NaN
3        104       pencil      5      150.0
4        105       eraser      8        NaN

In [20]:
pd.merge(products,sales, how='right')

   ProductID product name  price  UnitsSold
0        101          pen   10.0        500
1        102     notebook   50.0        200
2        104       pencil    5.0        150
3        106          NaN    NaN         50

In [21]:
pd.merge(products,sales,how='inner')

   ProductID product name  price  UnitsSold
0        101          pen     10        500
1        102     notebook     50        200
2        104       pencil      5        150

In [22]:
pd.merge(products,sales, how='cross')

    ProductID_x product name  price  ProductID_y  UnitsSold
0           101          pen     10          101        500
1           101          pen     10          102        200
2           101          pen     10          104        150
3           101          pen     10          106         50
4           102     notebook     50          101        500
5           102     notebook     50          102        200
6           102     notebook     50          104        150
7           102     notebook     50          106         50
8           103       marker     30          101        500
9           103       marker     30          102        200
10          103       marker     30          104        150
11          103       marker     30          106         50
12          104       pencil      5          101        500
13          104       pencil      5          102        200
14          104       pencil      5          104        150
15          104       pencil      5          106         50
16          105       eraser      8          101        500
17          105       eraser      8          102        200
18          105       eraser      8          104        150
19          105       eraser      8          106         50

In [24]:
pd.merge(products,sales, how='left')

   ProductID product name  price  UnitsSold
0        101          pen     10      500.0
1        102     notebook     50      200.0
2        103       marker     30        NaN
3        104       pencil      5      150.0
4        105       eraser      8        NaN

In [25]:
pd.merge(products,sales, how='outer') #gives all

   ProductID product name  price  UnitsSold
0        101          pen   10.0      500.0
1        102     notebook   50.0      200.0
2        103       marker   30.0        NaN
3        104       pencil    5.0      150.0
4        105       eraser    8.0        NaN
5        106          NaN    NaN       50.0

In [26]:
''' 
using join() with index alignment
*join() joins dataframes on their index or on a key column
by default, join on index can specify on='col' 
* useful for adding columns to an existring dataframe'''
stock = pd.DataFrame({
    'Stock':[100,60,80,120,150]
},index = [101,102,103,104,105])

In [30]:
pdata = products.set_index("ProductID")
pdata

          product name  price
ProductID
101                pen     10
102           notebook     50
103             marker     30
104             pencil      5
105             eraser      8

In [31]:
pdata.join(stock)

          product name  price  Stock
ProductID
101                pen     10    100
102           notebook     50     60
103             marker     30     80
104             pencil      5    120
105             eraser      8    150

In [34]:
sales = pd.DataFrame({
    'ProductID':[201,202,203,204],
    'UnitsSold':[500,300,400,250],
    
})
revenue = pd.DataFrame({
    'ProductID':[201,202,203,205],
    'Revenue':[7500,4500,6800,1200]
})
merged_df = pd.merge(sales, revenue, on="ProductID", how='outer')
merged_df

   ProductID  UnitsSold  Revenue
0        201      500.0   7500.0
1        202      300.0   4500.0
2        203      400.0   6800.0
3        204      250.0      NaN
4        205        NaN   1200.0