In [2]:
import pandas as pd

In [3]:
'''
1.using concat() for stacking data
* pd.concate() combine dataframes vertically or horizontally
use axis=0 for vertical stacking default, axis=1 for horizontal.
ignore_index = true can reset the index after concatenation'''
df1 = pd.DataFrame({
    "ProductID" : [101,102,103],
    "product name": ["pen", "notebook",'marker'],
    'price':[10,50,30]
})
df2 = pd.DataFrame({
    'ProductID' : [104,105],
    'product name':['pencil','eraser'],
    'price':[5,8]
})
df3 = pd.DataFrame({
    'stock':[100,60,80],
    'rating':[4.5,4.7,4.8]
})

In [9]:
print(df1)
print(df2)
print(df3)

   ProductID product name  price
0        101          pen     10
1        102     notebook     50
2        103       marker     30
   ProductID product name  price
0        104       pencil      5
1        105       eraser      8
   stock  rating
0    100     4.5
1     60     4.7
2     80     4.8

In [4]:
pd.concat([df1,df2])

   ProductID product name  price
0        101          pen     10
1        102     notebook     50
2        103       marker     30
0        104       pencil      5
1        105       eraser      8

In [5]:
pd.concat([df1,df2],ignore_index=True)

   ProductID product name  price
0        101          pen     10
1        102     notebook     50
2        103       marker     30
3        104       pencil      5
4        105       eraser      8

In [6]:
pd.concat([df1,df3]) #get nan when we have unsimilar data

   ProductID product name  price  stock  rating
0      101.0          pen   10.0    NaN     NaN
1      102.0     notebook   50.0    NaN     NaN
2      103.0       marker   30.0    NaN     NaN
0        NaN          NaN    NaN  100.0     4.5
1        NaN          NaN    NaN   60.0     4.7
2        NaN          NaN    NaN   80.0     4.8

In [10]:
pd.concat([df1,df3], axis=1) #concate horizantally, hence not get nan

   ProductID product name  price  stock  rating
0        101          pen     10    100     4.5
1        102     notebook     50     60     4.7
2        103       marker     30     80     4.8

In [11]:
''' 
using merge() for SQL-style joins
* merge() is similar to sql joins
* specify on or left_on/right_on to choose key columns
* join types: inner default, left, right, outer'''
products = pd.concat([df1,df2], ignore_index=True)
products

   ProductID product name  price
0        101          pen     10
1        102     notebook     50
2        103       marker     30
3        104       pencil      5
4        105       eraser      8

In [12]:
sales = pd.DataFrame({
    'productID': [101,102,104,106], #106 doesnt exist in products
    'UnitsSold':[500,200,150,50]
})

In [ ]:
pd.merge(products, sales, left_on='ProductID', right_on='productID')

MergeError: No common columns to perform merge on. Merge options: left_on=None, right_on=None, left_index=False, right_index=False