In [3]:
import numpy as np
import pandas as pd

In [4]:
#series and dataframe
#creating a series 
a = [10,20,30,40]
s = pd.Series(a)
s

0    10
1    20
2    30
3    40
dtype: int64

In [6]:
s = pd.Series(a, name='marks')
s

0    10
1    20
2    30
3    40
Name: marks, dtype: int64

In [12]:
d = {'akarsh':90,'harsha':12,'prithvi':34, 'vedant':50}
s2 = pd.Series(d, name='marks')
s2

akarsh     90
harsha     12
prithvi    34
vedant     50
Name: marks, dtype: int64

In [13]:
#creating dataframe
a = {
    'Name' : ['alice','bob','charlie','devid'],
    'marks': [90,85,78,92],
    'subject':['math','science','histogram','english']
}
df = pd.DataFrame(a)
df

      Name  marks    subject
0    alice     90       math
1      bob     85    science
2  charlie     78  histogram
3    devid     92    english

In [18]:
#creating data from from numpy arrays
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
df = pd.DataFrame(a, columns=['A','B','C'],index=['a','b','c'])
df

   A  B  C
a  1  2  3
b  4  5  6
c  7  8  9

In [20]:
#basics of dataframe
#inspecting data 
'''quick ways to understand the data'''
a ={
    'name':['nachiket','aditya','aman','mallu','alean'],
    'age' :[21,22,19,20,30],
    'score' :[91,89,75,80,69]
}
df = pd.DataFrame(a)
df

       name  age  score
0  nachiket   21     91
1    aditya   22     89
2      aman   19     75
3     mallu   20     80
4     alean   30     69

In [22]:
print(df.head()) #to get top 5 rows default, 
print(df.head(2)) #gives 2 rows

       name  age  score
0  nachiket   21     91
1    aditya   22     89
2      aman   19     75
3     mallu   20     80
4     alean   30     69
       name  age  score
0  nachiket   21     91
1    aditya   22     89

In [23]:
print(df.tail()) #give last 5 rows
print(df.tail(2)) #gives last 2

       name  age  score
0  nachiket   21     91
1    aditya   22     89
2      aman   19     75
3     mallu   20     80
4     alean   30     69
    name  age  score
3  mallu   20     80
4  alean   30     69

In [ ]:
print(df.info()) #give column. numbers, and dtypes size of data

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   name    5 non-null      object
 1   age     5 non-null      int64
 2   score   5 non-null      int64
dtypes: int64(2), object(1)
memory usage: 252.0+ bytes
None

In [29]:
df.shape #this is an attribute we won;t use (), it will give number of row and column

(5, 3)

In [ ]:
df.dtypes #it's also an attribute, gives data type of each column

name     object
age       int64
score     int64
dtype: object

In [31]:
#selecting columns and rows
df['name']

0    nachiket
1      aditya
2        aman
3       mallu
4       alean
Name: name, dtype: object

In [32]:
df['age']

0    21
1    22
2    19
3    20
4    30
Name: age, dtype: int64

In [33]:
#we can also use . operator to access
df.name

0    nachiket
1      aditya
2        aman
3       mallu
4       alean
Name: name, dtype: object

In [36]:
#for multiple columns
df[['name','score']] #we need to use [[]] and mention columns we we want to see

       name  score
0  nachiket     91
1    aditya     89
2      aman     75
3     mallu     80
4     alean     69

In [ ]:
#lable based selection
print(df)
print(df.loc[0])
print(type(df.loc[0])) #it is a series of one row
print(df.loc[2])
print(df.loc[[0,2]]) #to extract row and column it simply means
#df.loc[[row_lab, col_lab]]
print(df.loc[0:2,['name','score']]) #end point included.

       name  age  score
0  nachiket   21     91
1    aditya   22     89
2      aman   19     75
3     mallu   20     80
4     alean   30     69
name     nachiket
age            21
score          91
Name: 0, dtype: object
<class 'pandas.core.series.Series'>
name     aman
age        19
score      75
Name: 2, dtype: object
       name  age  score
0  nachiket   21     91
2      aman   19     75
       name  score
0  nachiket     91
1    aditya     89
2      aman     75

In [49]:
#integer based indexing
print(df)
print(df.iloc[0])
print(df.iloc[0:2])
#df.iloc[row_ind,col_ind]
print(df.iloc[0:3,1:3])

       name  age  score
0  nachiket   21     91
1    aditya   22     89
2      aman   19     75
3     mallu   20     80
4     alean   30     69
name     nachiket
age            21
score          91
Name: 0, dtype: object
       name  age  score
0  nachiket   21     91
1    aditya   22     89
   age  score
0   21     91
1   22     89
2   19     75

In [ ]:
#index and columns overview
df.index #give start end step values

RangeIndex(start=0, stop=5, step=1)

In [52]:
df.columns

Index(['name', 'age', 'score'], dtype='object')

In [ ]:
df.values #it will create an array consists of all element of df

array([['nachiket', 21, 91],
       ['aditya', 22, 89],
       ['aman', 19, 75],
       ['mallu', 20, 80],
       ['alean', 30, 69]], dtype=object)

In [58]:
#renaming columns
df.rename(columns={'score':'marks'}, inplace=True)

In [59]:
df

       name  age  marks
0  nachiket   21     91
1    aditya   22     89
2      aman   19     75
3     mallu   20     80
4     alean   30     69

In [63]:
#column as index
df.set_index('name', inplace=True)

KeyError: "None of ['name'] are in the columns"

In [64]:
df

          age  marks
name
nachiket   21     91
aditya     22     89
aman       19     75
mallu      20     80
alean      30     69

In [65]:
df.reset_index(inplace=True)

In [66]:
df

       name  age  marks
0  nachiket   21     91
1    aditya   22     89
2      aman   19     75
3     mallu   20     80
4     alean   30     69

In [ ]:
#practice 
'''
1.Create a DataFrame with at least 5 rows and 4 columns (mix of numeric + text).
2.Show the first 3 rows, last 2 rows, and the info.
3.Select a sub-DataFrame with only 2 columns.
4.Rename one column and set any column as index, then reset it back.
5.Print df.shape, df.dtypes, and df.columns.
'''

In [67]:
data = {
    "Name": ["Alice", "Bob", "Charlie", "David", "Emma"],
    "Age": [25, 30, 35, 40, 22],
    "City": ["Delhi", "Mumbai", "Pune", "Bangalore", "Chennai"],
    "Score": [85, 91, 78, 88, 95]
}

df = pd.DataFrame(data)
df

      Name  Age       City  Score
0    Alice   25      Delhi     85
1      Bob   30     Mumbai     91
2  Charlie   35       Pune     78
3    David   40  Bangalore     88
4     Emma   22    Chennai     95

In [69]:
print(df.head(3))
print(df.tail(2))
print(df.info())

      Name  Age    City  Score
0    Alice   25   Delhi     85
1      Bob   30  Mumbai     91
2  Charlie   35    Pune     78
    Name  Age       City  Score
3  David   40  Bangalore     88
4   Emma   22    Chennai     95
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    5 non-null      object
 1   Age     5 non-null      int64
 2   City    5 non-null      object
 3   Score   5 non-null      int64
dtypes: int64(2), object(2)
memory usage: 292.0+ bytes
None

In [70]:
df.iloc[0:,0:2]

      Name  Age
0    Alice   25
1      Bob   30
2  Charlie   35
3    David   40
4     Emma   22

In [75]:
df.rename(columns={'Score':'marks'}, inplace=True)
df

      Name  Age       City  marks
0    Alice   25      Delhi     85
1      Bob   30     Mumbai     91
2  Charlie   35       Pune     78
3    David   40  Bangalore     88
4     Emma   22    Chennai     95

In [84]:
df.set_index(['Name'], inplace=True)

In [85]:
df

         Age       City  marks
Name
Alice     25      Delhi     85
Bob       30     Mumbai     91
Charlie   35       Pune     78
David     40  Bangalore     88
Emma      22    Chennai     95

In [86]:
df.reset_index(inplace=True)

In [87]:
df

      Name  Age       City  marks
0    Alice   25      Delhi     85
1      Bob   30     Mumbai     91
2  Charlie   35       Pune     78
3    David   40  Bangalore     88
4     Emma   22    Chennai     95

In [89]:
print(df.shape)
print(df.columns)
print(df.values)
print(df.dtypes)

(5, 4)
Index(['Name', 'Age', 'City', 'marks'], dtype='object')
[['Alice' 25 'Delhi' 85]
 ['Bob' 30 'Mumbai' 91]
 ['Charlie' 35 'Pune' 78]
 ['David' 40 'Bangalore' 88]
 ['Emma' 22 'Chennai' 95]]
Name     object
Age       int64
City     object
marks     int64
dtype: object