In [1]:
import pandas as pd
import numpy as np

In [15]:
data = {
    "product":['pen','notebook','pencil','marker','earser','sharpener'],
    'price':[10,50,5,30,8,12],
    'stock':[100,100,200,90,150,120],
    'rating':[4.5,4.6,4.8,4.3,4.4,3.8]
}
df = pd.DataFrame(data)
df

     product  price  stock  rating
0        pen     10    100     4.5
1   notebook     50    100     4.6
2     pencil      5    200     4.8
3     marker     30     90     4.3
4     earser      8    150     4.4
5  sharpener     12    120     3.8

In [16]:
df.sort_values(by='price',ascending=False)

     product  price  stock  rating
1   notebook     50    100     4.6
3     marker     30     90     4.3
5  sharpener     12    120     3.8
0        pen     10    100     4.5
4     earser      8    150     4.4
2     pencil      5    200     4.8

In [17]:
df.sort_values(by='price')

     product  price  stock  rating
2     pencil      5    200     4.8
4     earser      8    150     4.4
0        pen     10    100     4.5
5  sharpener     12    120     3.8
3     marker     30     90     4.3
1   notebook     50    100     4.6

In [18]:
df.sort_values(by='product', ascending=False)

     product  price  stock  rating
5  sharpener     12    120     3.8
2     pencil      5    200     4.8
0        pen     10    100     4.5
1   notebook     50    100     4.6
3     marker     30     90     4.3
4     earser      8    150     4.4

In [ ]:
#sort multiple columns
df.sort_values(by=['price','stock'], ascending=[True,False])
#first priority is price then stock

     product  price  stock  rating
2     pencil      5    200     4.8
4     earser      8    150     4.4
0        pen     10    100     4.5
5  sharpener     12    120     3.8
3     marker     30     90     4.3
1   notebook     50    100     4.6

In [21]:
#descriptive statistics 
df.mean(numeric_only=True)

price      19.166667
stock     126.666667
rating      4.400000
dtype: float64

In [22]:
#or
df.select_dtypes('number').mean()

price      19.166667
stock     126.666667
rating      4.400000
dtype: float64

In [23]:
df.median(numeric_only=True)

price      11.00
stock     110.00
rating      4.45
dtype: float64

In [24]:
df.std(numeric_only=True)

price     17.486185
stock     41.793141
rating     0.340588
dtype: float64

In [26]:
df.describe()

           price       stock    rating
count   6.000000    6.000000  6.000000
mean   19.166667  126.666667  4.400000
std    17.486185   41.793141  0.340588
min     5.000000   90.000000  3.800000
25%     8.500000  100.000000  4.325000
50%    11.000000  110.000000  4.450000
75%    25.500000  142.500000  4.575000
max    50.000000  200.000000  4.800000

In [27]:
#value counts show frequency in a series
df['product'].value_counts()

product
pen          1
notebook     1
pencil       1
marker       1
earser       1
sharpener    1
Name: count, dtype: int64

In [28]:
df['product'].value_counts(normalize=True) #normalize =True used to get percentage

product
pen          0.166667
notebook     0.166667
pencil       0.166667
marker       0.166667
earser       0.166667
sharpener    0.166667
Name: proportion, dtype: float64

In [29]:
#correlation and covariance
df.corr(numeric_only=True)

           price     stock    rating
price   1.000000 -0.609376  0.094029
stock  -0.609376  1.000000  0.407468
rating  0.094029  0.407468  1.000000

In [30]:
df.cov(numeric_only=True)

             price        stock  rating
price   305.766667  -445.333333   0.560
stock  -445.333333  1746.666667   5.800
rating    0.560000     5.800000   0.116

In [31]:
'''Build a DataFrame with columns: Name, Age, Score, Height.
Sort the data by Score (descending).
Get mean, median, mode, and std of numeric columns.
Use value_counts on Name or any categorical column.
Compute corr() and cov() for all numeric columns.'''

'Build a DataFrame with columns: Name, Age, Score, Height.\nSort the data by Score (descending).\nGet mean, median, mode, and std of numeric columns.\nUse value_counts on Name or any categorical column.\nCompute corr() and cov() for all numeric columns.'

In [32]:
data = {
    'name':['nachiket','mallu','chanty','samee','mantesh'],
    'Age':[19,20,22,19,25],
    'score':[91,78,43,57,90],
    'height':[148.3,154.2,140,144.4,145.5]
}
df = pd.DataFrame(data)
df

       name  Age  score  height
0  nachiket   19     91   148.3
1     mallu   20     78   154.2
2    chanty   22     43   140.0
3     samee   19     57   144.4
4   mantesh   25     90   145.5

In [33]:
df.sort_values(by='score', ascending=False)

       name  Age  score  height
0  nachiket   19     91   148.3
4   mantesh   25     90   145.5
1     mallu   20     78   154.2
3     samee   19     57   144.4
2    chanty   22     43   140.0

In [35]:
print(df.mean(numeric_only=True))
print(df.median(numeric_only=True))
print(df.std(numeric_only=True))
print(df.corr(numeric_only=True))
print(df.describe())

Age        21.00
score      71.80
height    146.48
dtype: float64
Age        20.0
score      78.0
height    145.5
dtype: float64
Age        2.549510
score     21.135279
height     5.248524
dtype: float64
             Age     score    height
Age     1.000000  0.134547 -0.328820
score   0.134547  1.000000  0.636398
height -0.328820  0.636398  1.000000
            Age      score      height
count   5.00000   5.000000    5.000000
mean   21.00000  71.800000  146.480000
std     2.54951  21.135279    5.248524
min    19.00000  43.000000  140.000000
25%    19.00000  57.000000  144.400000
50%    20.00000  78.000000  145.500000
75%    22.00000  90.000000  148.300000
max    25.00000  91.000000  154.200000

In [36]:
df.name.value_counts()

name
nachiket    1
mallu       1
chanty      1
samee       1
mantesh     1
Name: count, dtype: int64

In [37]:
df.corr(numeric_only=True)

             Age     score    height
Age     1.000000  0.134547 -0.328820
score   0.134547  1.000000  0.636398
height -0.328820  0.636398  1.000000

In [38]:
df.cov(numeric_only=True)

         Age    score  height
Age     6.50    7.250  -4.400
score   7.25  446.700  70.595
height -4.40   70.595  27.547