In [16]:
''' 
converting columns to datetime
use pd.to_datetime() to convert strings or numbers into datetime objects
once converted, pandas recognizes them as dates, enabling powerful operations'''
import pandas as pd
data = {
    'orderID':[1001,1002,1003,1004,1005],
    'orderdate':['2024-01-05','2024/01/12','15-01-2024','2024-01-20','20240125'],
    'customer':['alice','bob','charlie','david','emma'],
    'amount':[250,400,150,300,500]
    
}
df = pd.DataFrame(data)
df

   orderID   orderdate customer  amount
0     1001  2024-01-05    alice     250
1     1002  2024/01/12      bob     400
2     1003  15-01-2024  charlie     150
3     1004  2024-01-20    david     300
4     1005    20240125     emma     500

In [17]:
df.dtypes

orderID       int64
orderdate    object
customer     object
amount        int64
dtype: object

In [18]:
pd.to_datetime(df['orderdate']) #we must convert the date in a format to apply changes

ValueError: time data "2024/01/12" doesn't match format "%Y-%m-%d", at position 1. You might want to try:
    - passing `format` if your strings have a consistent format;
    - passing `format='ISO8601'` if your strings are all ISO8601 but not necessarily in exactly the same format;
    - passing `format='mixed'`, and the format will be inferred for each element individually. You might want to use `dayfirst` alongside this.

In [19]:
df['orderdate'] = pd.to_datetime(df['orderdate'],errors='coerce') #remove errored data and give unerrored data

In [22]:
''' 
2.setting datetime index and resampling
* set a datetime column as the index with set_index(),
* resample time series using resample('M').mean() or other rules ('D','W','Y')
useful for aggregating data by time periods.
'''
df_idex = df.set_index("orderdate")
df_idex

            orderID customer  amount
orderdate
2024-01-05     1001    alice     250
NaT            1002      bob     400
NaT            1003  charlie     150
2024-01-20     1004    david     300
NaT            1005     emma     500

In [26]:
df_idex.resample('M')['amount'].sum()

C:\Users\nachi\AppData\Local\Temp\ipykernel_5072\1064612877.py:1: FutureWarning: 'M' is deprecated and will be removed in a future version, please use 'ME' instead.
  df_idex.resample('M')['amount'].sum()

orderdate
2024-01-31    550
Name: amount, dtype: int64